# Generated by Django 5.0.1 on 2024-02-06 13:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=5, unique=True)),
                ('date', models.DateTimeField()),
                ('customer', models.CharField(max_length=30)),
                ('customer_image', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=11)),
                ('subject', models.CharField(max_length=255)),
                ('comment', models.CharField(max_length=255)),
                ('published', models.BooleanField(verbose_name='Is published?')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=5, unique=True)),
                ('room_type', models.CharField(choices=[('single_bed', 'Single Bed'), ('double_bed', 'Double Bed'), ('double_superior', 'Double Superior'), ('suite', 'Suite')], max_length=15)),
                ('room_number', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('amenities', models.JSONField()),
                ('cancellation', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('offer', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99), django.core.validators.MinValueValidator(0)])),
                ('available', models.BooleanField(verbose_name='Is available?')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(max_length=5, unique=True)),
                ('guest', models.CharField(max_length=30)),
                ('guest_image', models.CharField(max_length=255)),
                ('order_date', models.DateTimeField()),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('special_request', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('in_progress', 'In Progress')], max_length=11)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelMiranda.room')),
            ],
        ),
    ]
