# Generated by Django 5.0.1 on 2024-02-06 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelMiranda', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_id',
            new_name='room',
        ),
    ]
