# Generated by Django 5.0.1 on 2024-02-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelMiranda', '0002_rename_room_id_booking_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='comment',
            field=models.CharField(max_length=1024),
        ),
    ]
