# Generated by Django 5.0.1 on 2024-02-10 12:08

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelMiranda', '0003_alter_contact_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='customer_image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 10, 13, 8, 46, 236588)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Invalid phone number, you have to put with this format: 999 999 999', regex='[6-9][0-9]{2} [0-9]{3} [0-9]{3}')]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Is published?'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=30),
        ),
    ]
