# Generated by Django 5.0.1 on 2024-02-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelMiranda', '0006_alter_contact_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
