# Generated by Django 5.0.1 on 2024-02-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelMiranda', '0007_alter_booking_email_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='special_request',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
