

name: Build and deploy API

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v4

      - name: Pull a code
        run: git pull

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            script: cd HotelMirandaDjango &&
                    source env/bin/activate &&
                    pip install -r requirements.txt &&
                    python manage.py makemigrations &&
                    python manage.py migrate &&
                    sudo systemctl restart nginx &&
                    sudo systemctl restart gunicorn

